/* Automatically generated by configure - do not modify! */
#define FFMPEG_CONFIGURATION " "

#define TUNECPU generic

#define HAVE_BUILTIN_VECTOR 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LRINTF 1

#define CONFIG_DECODERS 1

#define HAVE_MALLOC_H 1

#define SIMPLE_IDCT 1

#define restrict

#define CONFIG_H264_DECODER 1


